
spring:
  profiles:
    # 激活当前配置为dev
    active: dev


mybatis:
  # 配置mybatis映射的别名
  type-aliases-package: com.fanyi.andnow.entity

# 设置mybatis将sql打印到控制台
#mybatis.mapper-locations=classpath:com/fanyi/andnow/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置将sql打印到控制台，level下配置mapper对应的包名
#logging:
#  level:
#    com.fan1111.material: DEBUG

