
spring:
  profiles:
    # 激活当前配置为dev
    active: dev


mybatis:
  # 配置mybatis映射的别名
  type-aliases-package: com.fanyi.andnow.common.vo

# 设置mybatis将sql打印到控制台
#mybatis.mapper-locations=classpath:com/fanyi/scm/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置将sql打印到控制台，level下配置mapper对应的包名
#logging:
#  level:
#    com.fan1111.mapper: DEBUG


---
# 开发环境配置
spring:
  profiles: dev
  # 配置数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.fan1111.com:3306/dbscm?useSSL=false
    username: dbscm
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

#配置集成tomcat的端口，可自行修改
server:
  port: 2888




---
# 生产环境配置
spring:
  profiles: prod
  # 配置数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.fan1111.com:3306/dbscm?useSSL=false
    username: dbscm
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

#配置集成tomcat的端口，可自行修改
server:
  port: 8888


